### ISSUE TITLE
the fragment load twice

### ISSUE THREAD

**Issue by whao189** [Intelliabb/android#1]
when use the code 
like this :
```
ArrayList<Tab> list = new ArrayList<Tab>();
Tab1  tb1 = new Tab1();
Tab2  tb2 = new Tab2();
Tab3  tb3 = new Tab3();

list.add(tab1);
list.add(tab2);
list.add(tab3);

tabHost.add(new TabsInfo(Tab1.class, null));
tabHost.add(new TabsInfo(Tab2.class, null));
tabHost.add(new TabsInfo(Tab1.class, null));

MviewPagerAdapter adapter = new MviewPagerAdapter(this, list);

in  this file "MviewPagerAdapter"  the code :
@Override
    public Fragment getItem(int position) {
               return list.get(1);
    }


```
so , the classes, Tab1  Tab2 Tab3 will instance  twice,  

first instance : Tab1  tb1 = new Tab1();
twice instance : tabHost.add(new TabsInfo(Tab1.class, null));

how to resolve it ????  

have you any way ?

**Comment by Intelliabb** [comment]
The line
`Tab1 tb1 = new Tab1();`
will create a new instance of `Tab1` class. Whereas the 
`tabHost.add(new TabsInfo(Tab1.class, null));`
line creates a new instance of `TabsInfo()` using `Tab1()` class instance for the tab host.
Where are you seeing (in memory) the classes being instantiated twice?

**Comment by whao189** [comment]
yes , the source code 

in the file of   FragmentTabHost.java ,  method is "doTabChanged "

`if (newTab != null) {
                if (newTab.fragment == null) {
                    newTab.fragment = ## Fragment.instantiate(mContext,
                            newTab.clss.getName(), newTab.args);
                    ft.add(mContainerId, newTab.fragment, newTab.tag);
                } else {
                    ft.attach(newTab.fragment);
                }
            }
`
`public static Fragment instantiate(Context context, String fname, @Nullable Bundle args) {
        try {
            Class<?> clazz = sClassMap.get(fname);
            if (clazz == null) {
                // Class not found in the cache, see if it's real, and try to add it
                clazz = context.getClassLoader().loadClass(fname);
                sClassMap.put(fname, clazz);
            }
            Fragment f = (Fragment)clazz.newInstance();
            if (args != null) {
                args.setClassLoader(f.getClass().getClassLoader());
                f.mArguments = args;
            }
            return f;`

in my project , i print the log, within the Tab1.class, Tab1.class---> onCreateView {
log.i (TAG,"------------"+this.toString());
}

the log print twice , 
first :Tab1  tb1 = new Tab1();
second : tabHost.add(new TabsInfo(Tab1.class, null));


you can try it .... thk

**Comment by Intelliabb** [comment]
Just realized the issue is with how you are initializing your tabs and not my code in this repo. 

In the sample here, I don't initialize my tabs (or fragments) explicitly. The TabHost will create the fragment on demand. Is there a reason behind explicitly initializing your tabs?

If not, remove the `Tab1 tb1 = new Tab1();` for your tabs and let tabHost create them for you. Try it and let me know if it works for you.

**Comment by whao189** [comment]
yeah , i see.  if i remove the  Tab1 tb1 = new Tab1();  it work !

but when i instance MviewPagerAdapter, the param list of MviewPagerAdapter , the "list", how should i fill 

it???

if i  remove Tab1 tb1 = new Tab1();  the list , i can't filling it , then the MviewPagerAdapter can't initalize,

tabHost.add(new TabsInfo(Tab1.class, null))  works well.
